### ISSUE TITLE
Playground not building

### ISSUE THREAD

**Issue by bryan-aguilar** [GEOSwift/GEOSwiftMapKit#13]
Relatively new to swift development so I apologize in advance if I am missing info or made a glaring mistake. I am currently trying to integrate GEOSwiftMapKit into an existing project. Before fully adopting it I was hoping to utilize the given playground but I cannot get it to build correctly in Xcode. 

Swift --version
`Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: arm64-apple-darwin20.6.0`

xed --version
`xed version 12.5.1`

M1 Mac mini

Steps I took:
1. Cloned repository
2. opened with `xed Package.swift`
3. No scheme was present to build for
4. When opening playground I get a `No Such module geoswift exists`
5. Package dependencies do show up
![image](https://user-images.githubusercontent.com/46550959/133524920-1f40feb3-8824-466c-8fdc-f2781e3dcbff.png)

1. Opened by selecting the GEOSwiftMapkit.xcodeproj file
2. GEOSwiftMapKit-ios scheme does show up
3. Received errors below
![image](https://user-images.githubusercontent.com/46550959/133524747-af193177-ee82-4281-ae7a-087696410da3.png)
4. Added package dependencies for GEOSwift and geos but the framework errors persisted.

**Comment by bryan-aguilar** [comment]
I managed to get this to work and I am unsure if there is still an error or the documentation could be improved. 
Off of a clean clone check the `Build Active Scheme` option in the playground file. 

![image](https://user-images.githubusercontent.com/46550959/133709337-90e10542-ddde-4cf8-a5ae-70ba97512600.png)

Doing anything else to the project will cause errors. Since I am unfamiliar with the swift dependency system I am unsure if this is as expected. I will leave this open until as a reference until a maintainer deems it's closed.

**Comment by macdrevx** [comment]
Thanks @bryan-aguilar! I've incorporated your recommendations along with a few other changes. I'll be merging them into main later today and releasing a new version that contains some other changes as well. See the updated readme for the new instructions for using the playground, and let me know if you notice anything else not working.
