### ISSUE TITLE
Compiling error when enabling Mac Catalyst in iOS target

### ISSUE THREAD

**Issue by GerdC** [GEOSwift/GEOSwiftMapKit#14]
To reproduce:
- In Xcode project target, enable Mac Catalyst
- Compile a project that imports GEOSwift.

In file GeoSwift+MapKitQuickLook the compiler fails this with message "'Polygon' is ambiguous for type lookup in this context"

once in
extension Polygon.LinearRing: GEOSwiftQuickLook {

and once in
extension Polygon: GEOSwiftQuickLook {

**Comment by macdrevx** [comment]
This will be fixed in v4 (coming later today)
