### ISSUE TITLE
Update GEOSwift dependency to 9.0.0

### ISSUE THREAD

**Issue by nicobayer** [GEOSwift/GEOSwiftMapKit#15]
Hello folks, latest version of GEOSwift has been 9.0.0 for a year now, wondering if there is any reason not to update dependency of this pod to that version. Currently using GEOSwiftMapKit locks you on 8.x.x. Cheers!

**Comment by macdrevx** [comment]
Yes, we should do it! We'll try to do a round of updates by the end of the year. Feel free to open a PR if you have time to do it before then.

**Comment by macdrevx** [comment]
I recently updated GEOSwift to 10. There's a new release of GEOSwiftMapKit coming today that will use that version.
