### ISSUE TITLE
Add support for GEOSwift 5.1

### ISSUE THREAD

**Issue by dasilva-carlos** [GEOSwift/GEOSwiftMapKit#2]
When CocoaPods tries to install the library, the following message is displayed:

[!] CocoaPods could not find compatible versions for pod "GEOSwift":
  In snapshot (Podfile.lock):
    GEOSwift (= 5.1.0)

  In Podfile:
    GEOSwift

    GEOSwiftMapKit was resolved to 1.0.0, which depends on
      GEOSwift (= 5.0.0)

PS: The CocoaPods version is 1.8.3

**Comment by macdrevx** [comment]
Hi, can you attach a sample project that reproduces the issue?

Also, I wonder whether you just need to `$ pod repo update`

**Comment by dasilva-carlos** [comment]
You are absolutely right. Thank you for your help.
