### ISSUE TITLE
1.0.0 is not compatible with GEOSwift version 5.2

### ISSUE THREAD

**Issue by borut-t** [GEOSwift/GEOSwiftMapKit#5]
```
s.dependency 'GEOSwift', '5.0.0'
```
Dependency is set to version `5.0.0` ☝️ , but `5.2.0` is already released. Can you update it?

**Comment by macdrevx** [comment]
Yep, will do. Duplicate of #3

**Comment by borut-t** [comment]
What’s the ETA on release?

**Comment by macdrevx** [comment]
I can take care of it this week.

**Comment by macdrevx** [comment]
@borut-t I just released 1.1.0 and it fixes this issue. Let me know if it works for you.

**Comment by borut-t** [comment]
@macdrevx it works. Thanks for quick action.
